version: "2"

services:

  bot:
    build:
      context: ./checkbox451_bot
      args:
        TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
        TELEGRAM_BOT_ADMIN: $TELEGRAM_BOT_ADMIN
        CHECKBOX_LOGIN: $CHECKBOX_LOGIN
        CHECKBOX_PASSWORD: $CHECKBOX_PASSWORD
        CHECKBOX_LICENSE: $CHECKBOX_LICENSE
        CHECKBOX_API_URL: $CHECKBOX_API_URL
        PRINTER_CONFIG: $PRINTER_CONFIG
        PRINT_WIDTH: $PRINT_WIDTH
        PRINT_BOTTOM_MARGIN: $PRINT_BOTTOM_MARGIN
        PRINT_LOGO_PATH: $PRINT_LOGO_PATH
        PRINT_LOGO_IMPL: $PRINT_LOGO_IMPL
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
        GOOGLE_SPREADSHEET_KEY: $GOOGLE_SPREADSHEET_KEY
        GOOGLE_WORKSHEET_TITLE: $GOOGLE_WORKSHEET_TITLE
        DB_DIR: /db
    volumes:
      - db:/db
    restart: unless-stopped
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.shift_close.schedule: "0 0 22 * * *"
      ofelia.job-exec.shift_close.command: "python3 -m checkbox451_bot.shift_close"

  srso_signer:
    build:
      context: ./srso_signer
      args:
        LOGIN: $CHECKBOX_LOGIN
        API_URL: $CHECKBOX_API_URL
        KEY: $CHECKBOX_KEY_PATH
        PASSWORD: $CHECKBOX_KEY_PASS
        ACSK: $CHECKBOX_KEY_ACSK
    restart: unless-stopped

  ofelia:
    image: mcuadros/ofelia:latest
    environment:
      TZ: Europe/Kiev
    depends_on:
      - bot
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db:
